spring:
  datasource:
    url: jdbc:mysql://localhost:13306/auth
    driver-class-name: com.mysql.jdbc.Driver
    username: auth-user
    password: '{cipher}a29f73d5df6ac36fac700ba4bc28775b504762142f1cd6cc6a4edc45a6fa1b8e'
    initialization-mode: never

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      storage_engine: innodb
      format_sql: true
  main:
    allow-bean-definition-overriding: true
server:
  ssl:
    enabled: true
    key-store-type: JKS
    key-store: classpath:keystore.jks
    key-store-password: '{cipher}ae1d8860808824715b4c2503607a6bb2366df2123c3a1ca0dc4b9e0a322ab181'
    key-alias: selfsigned
    key-password: '{cipher}ae1d8860808824715b4c2503607a6bb2366df2123c3a1ca0dc4b9e0a322ab181'
  port: 18443
logging:
  level:
    org.springframework: DEBUG
#     org.springframework.security.web.FilterChainProxy: DEBUG

      
